# Generated by Django 6.0.2 on 2026-06-06 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100, unique=True)),
                ('response_data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
