# Generated by Django 6.0.2 on 2026-06-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_searchlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchLog',
        ),
    ]
